### ISSUE TITLE
Preprocessing script

### ISSUE THREAD

**Issue by gentaiscool** [iamyuanchung/Autoregressive-Predictive-Coding#4]
Hi, can you also share your preprocessing script to generate 80-dimensional log Mel spectrograms? Did you apply the same script to both Librispeech and WSJ? Thank you

**Comment by iamyuanchung** [comment]
Sorry for the late reply - somehow I missed the notification email.

Here's our conf for extracting the log Mel features. We extract features with Kaldi, and you can do the same with the script steps/make_fbank.sh. Note that due to dithering you won't get the exact same log Mel feature values. We also do speaker mean normalizing as mentioned in the paper.

--window-type=hamming
--use-energy=false
--dither=1
--num-mel-bins=80
--htk-compat=true

And yes, we preprocessed LibriSpeech and WSJ following the same configuration.
